---
branches:
only:
- master
language: ruby
bundler_args: --without system_tests
script: 'bundle exec rake test'
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 2.7.0" FACTER_GEM_VERSION="~> 1.6.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 2.7.0" FACTER_GEM_VERSION="~> 1.7.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.5" STRICT_VARIABLES="yes"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.5" STRICT_VARIABLES="yes"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.5" STRICT_VARIABLES="yes"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.6" STRICT_VARIABLES="yes"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.6" STRICT_VARIABLES="yes"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.6" STRICT_VARIABLES="yes"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.7" STRICT_VARIABLES="yes"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.7" STRICT_VARIABLES="yes"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.7" STRICT_VARIABLES="yes"